ministryofjustice/CFO-CaseAssessmentTrackingSystem

src/Server.UI/Components/Fusion/OnlineUsersTracker.razor, src/Server.UI/Components/Shared/Layout/SearchDialog.razor, src/Server.UI/Components/Stepper/CatsMudStepper.cs, src/Server.UI/Pages/Enrolments/Enrolment.razor, src/Server.UI/Pages/Identity/Roles/Roles.razor, src/Server.UI/Pages/Identity/Users/Users.razor, src/Server.UI/Pages/SystemManagement/Dictionaries.razor, src/Server.UI/Pages/Tenants/Tenants.razor, src/Server.UI/Server.UI.csproj, src/Server.UI/Services/DialogServiceHelper.cs
This updates the dependencies to be the newly released version of mudblazor 7.0 from mudblazor 7.*-rc
=> Update mudblazor from RC to full version

db/seed/001_development_seed.sql
Modify the seed script to include provider names now the contracts have been signed and published on the external public contract system.
- No attempt has been made to make the script idempotent.
=> Update seeding script

src/Application/Features/Assessments/DTOs/ParticipantAssessmentDto.cs, src/Application/Features/Assessments/Queries/GetAssessmentScores.cs, src/Server.UI/Pages/Participants/Components/RagBar.razor, src/Server.UI/Pages/Participants/Components/RagComponent.razor, src/Server.UI/Pages/Participants/Participant.razor
This gets the ragscores from the database and displays the latest one in the screen
=> Pull rag scores onto dashboard

src/Server.UI/Pages/Participants/Components/CaseSummary.razor
This is a small change to remove example cards from the participant dashboard
=> remove temporary cards

src/Server.UI/Constants/Theme.cs
This adjusts the red colour of the rag bar that was looking a bit orange.
=> Adjust ragbar red

src/Infrastructure/Extensions/SerilogExtensions.cs, src/Server.UI/Components/Shared/CustomError.razor, src/Server.UI/Properties/launchSettings.json, src/Server.UI/appsettings.Training.json, src/Server.UI/appsettings.json
- Hide error and stack trace if not in Development Environment
- Adjust launch settings so we can fire off a different environment from VS
- Adjust appsettings.config to comment out Sentry, as running in none dev environment attempts to use an invalid url due to user secrets not loading under this profile
=> Adjust the customerror component to hide exception

src/Application/Features/Participants/DTOs/ParticipantPaginationDto.cs, src/Application/Features/Participants/Queries/ParticipantsWithPaginationQuery.cs, src/Application/Features/Participants/Specifications/ParticipantAdvancedFilter.cs, src/Application/Features/Participants/Specifications/ParticipantAdvancedSpecification.cs, src/Server.UI/Pages/Participants/Participants.razor
- Model returned is smaller and doesn't touch documents and assessments
- Query filters correctly for drop down box
- Added addition data in result (owner, tenant)
- Users with additional roles can see other peoples work. (limited to their tenant and below)
=> Adjusted the pagination query

src/Infrastructure/Services/Candidates/DummyCandidateService.cs
Pull request to fix the case sensitivity of the participant search
=> Make candidate search ignore case

src/Server.UI/Pages/Participants/Components/ParticipantActionMenu.razor
Hides the option to abandon a case when it is not at a abandonable stage.
=> Do not show the option to abandon a case in QA stage.

.gitignore, src/Server.UI/Components/Stepper/StatusResultStep.razor, src/Server.UI/Pages/Assessment/Assessment.razor, src/Server.UI/Pages/Risk/Risk.razor
This change means the user can progress from the end of the assessment to the participant.
It also removes the previous button from the last step as this is not validm
=> Final screen when filling in an assessment

src/Server.UI/Pages/Assessment/Assessment.razor, src/Server.UI/Pages/Identity/Authentication/Login.razor
Go to top of the assessment when moving through
=> CFODEV-526-return-to-top-of-pages-when-entering-assessments

src/Server.UI/Server.UI.csproj, src/Server.UI/web.config
This adds a web.config to the web project that has settings in it to remove certain headers (and change others) as per app sec findings.
=> Add web.config for security headers

src/Infrastructure/Constants/ClaimTypes/ApplicationClaimTypes.cs, src/Infrastructure/DependencyInjection.cs, src/Infrastructure/Services/ApplicationUserClaimsPrincipalFactory.cs, src/Server.UI/Components/App.razor, src/Server.UI/Components/Redirections/RedirectToLogin.razor, src/Server.UI/Components/Shared/Layout/MainLayout.razor, src/Server.UI/Services/IdentityRevalidatingAuthenticationStateProvider.cs, src/Server.UI/appsettings.json
This will log the user out after a configurable settings (or 20 minutes if not set)
It will also check the users lockout status on every mediator call
=> Auto logout + check for lockout

src/Server.UI/Components/App.razor
This should result in less traffic to the timer.
=> use mouse down instead of move

src/Server.UI/Components/Shared/Layout/AuthenticationLayout.razor, src/Server.UI/Components/Shared/Layout/MainLayout.razor, src/Server.UI/Constants/Theme.cs, src/Server.UI/appsettings.json
Override the primary colour to allow different environments to be obvious.
=> Allow override of primary theme.

ModifyDatabase.ps1, cats.sln, db/seed/001_development_seed.sql, src/Application/Common/Interfaces/IApplicationDbContext.cs, src/Application/Features/Participants/Commands/CreateParticipant.cs, src/Application/Features/Participants/Commands/SetEnrolmentLocation.cs, src/Application/Features/Participants/DTOs/ParticipantSummaryDto.cs, src/Domain/Common/Enums/LocationType.cs, src/Domain/Entities/Administration/Location.cs, src/Domain/Entities/Participants/Participant.cs, src/Infrastructure/Persistence/ApplicationDbContext.cs, src/Infrastructure/Services/Candidates/DummyCandidateService.cs, src/Server.UI/Pages/Candidates/Components/CandidateFinderComponent.razor, src/Server.UI/Pages/Enrolments/Components/Location.razor, src/Server.UI/Pages/Enrolments/Enrolment.razor, src/Server.UI/Pages/Participants/Participant.razor
You are now forced to pick the contract location
=> CFODEV-597 - Locations and Enrolment Locations

src/Server.UI/Services/Layout/LayoutService.cs
This hotfix addresses an issue where the primary colour doesn't get c…hanged by environment when set in the layout service
=> Primary colour fix

src/Application/Features/Identity/DTOs/ApplicationUserDto.cs, src/Server.UI/Pages/Identity/Users/Users.razor
- The phone number now saves on create
- Two factor auth is enabled by default
- Set all users to 'false' for export and import
=> Addresses issues with user registration

src/Server.UI/Pages/Identity/Authentication/Login.razor
=> Ask browsers not to allow autocomplete on login

src/Application/Common/Interfaces/IApplicationDbContext.cs, src/Application/Features/Identity/DTOs/IdentityAuditTrailDto.cs, src/Application/Features/Identity/Notifications/IdentityEvents/IdentityAuditNotification.cs, src/Application/Features/Identity/Notifications/IdentityEvents/IdentityAuditNotificationHandler.cs, src/Application/Features/Identity/Notifications/SendTwoFactorCode/SendTwoFactorTextCodeNotificationHandler.cs, src/Application/Features/Identity/Queries/PaginationQuery/IdentityAuditTrailsWithPagination.cs, src/Application/Features/Identity/Specifications/IdentityAuditTrailAdvancedFilter.cs, src/Application/Features/Identity/Specifications/IdentityAuditTrailAdvancedSpecification.cs, src/Application/Features/Identity/Specifications/IdentityAuditTrailListView.cs, src/Domain/Entities/IdentityAuditTrail.cs, src/Infrastructure/Constants/Database/DatabaseConstants.cs, src/Infrastructure/Persistence/ApplicationDbContext.cs, src/Infrastructure/Persistence/Configurations/Audit/IdentityAuditTrailConfiguration.cs, src/Migrators/Migrators.MSSQL/Migrations/20240822102359_IdentityAudit.Designer.cs, src/Migrators/Migrators.MSSQL/Migrations/20240822102359_IdentityAudit.cs, src/Migrators/Migrators.MSSQL/Migrations/20240822123041_AuditIndexes.Designer.cs, src/Migrators/Migrators.MSSQL/Migrations/20240822123041_AuditIndexes.cs, src/Server.UI/Pages/Identity/Authentication/Login.razor, src/Server.UI/Pages/Identity/Authentication/LoginWith2fa.razor, src/Server.UI/Pages/Identity/Authentication/ResetPassword.razor, src/Server.UI/Pages/Identity/Users/Components/ResetPasswordDialog.razor, src/Server.UI/Pages/Identity/Users/Components/UserAuditDialog.razor, src/Server.UI/Pages/Identity/Users/Profile.razor, src/Server.UI/Pages/Identity/Users/Users.razor
This audits the main identity events
* also removed the ability to archive an account, we will not be deleting them.
=> Cfodev 312 record security events

src/Server.UI/Components/Shared/Layout/AppLayout.razor, src/Server.UI/Components/Shared/Layout/AuthenticationLayout.razor, src/Server.UI/appsettings.json
Add banner for environment if not in production, also add an optional pre-login message.
=> Add banner for environment

src/Infrastructure/Infrastructure.csproj, src/Infrastructure/Services/Identity/CustomSigninManager.cs
Ranges cannot be mentioned in tickets.
=> Uses a range.

src/Application/Features/Participants/Queries/GetParticipantIdentifiers.cs, src/Application/Features/Participants/Queries/GetParticipantSupervisor.cs
=> Sentence Information (feedback)

src/Infrastructure/Constants/ConstantString.cs, src/Server.UI/Pages/Participants/Components/ConsentDialog.razor, src/Server.UI/Pages/Participants/Components/ParticipantActionMenu.razor
it allows a user to add Consent outside of the enrolment process
=> Added a menu item 'Add Consent' to Participant screen>Actions menu, onclick it shows a dialog,

src/Application/Features/QualityAssurance/DTOs/EnrolmentQueueEntryDto.cs, src/Application/Features/QualityAssurance/Queries/PqaQueueWithPagination.cs, src/Application/Features/QualityAssurance/Queries/Qa1WithPagination.cs, src/Application/Features/QualityAssurance/Queries/Qa2WithPagination.cs, src/Server.UI/Pages/QA/Enrolments/Components/QA1List.razor, src/Server.UI/Pages/QA/Enrolments/Components/QA2List.razor, src/Server.UI/Pages/QA/Enrolments/PqaList.razor
Turns out dynamic queries not that great with nested properties
=> Fix sorting and paging on QA lists.

src/Application/Features/Participants/Commands/ChangeEnrolmentLocation.cs, src/Application/Features/Participants/DTOs/ParticipantSummaryDto.cs, src/Domain/Common/Enums/EnrolmentStatus.cs, src/Infrastructure/Constants/ConstantString.cs, src/Server.UI/Pages/Participants/Components/AdjustEnrolmentLocationDialog.razor, src/Server.UI/Pages/Participants/Components/CaseSummary.razor.cs, src/Server.UI/Pages/Participants/Components/ParticipantActionMenu.razor, src/Server.UI/Pages/Participants/Participant.razor
- only at Submitted to PQA stage and below
=> CFODEV-777: Allow enrolment location to change

.config/dotnet-tools.json, src/Application/Application.csproj, src/Domain/Domain.csproj, src/Infrastructure/Infrastructure.csproj, src/Server.UI/Server.UI.csproj, test/Application.UnitTests/Application.UnitTests.csproj, test/ArchitectureTests/ArchitectureTests.csproj
This updates the nuget packages to the latest version.
Checked the following
- Project runs
- Tests pass
- Able to enrol a participant.
=> update packages to latest versions

src/Server.UI/Components/Shared/Layout/MainLayout.razor
Should a user retain their session, when returning to the site should detect they've been gone for > x minutes and force them to log out
=> Force logout if session has been kept alive by chromium browsers

src/Application/Features/Payables/Commands/AddEducationTraining.cs, src/Server.UI/Pages/Payables/AddActivityDialog.razor, src/Server.UI/Pages/Payables/Components/EducationTraining.razor
Raising PR for 884, changes made by @vks333
=> CFODEV-884: Added command and form for Education and training, need more work

src/Application/Common/Validators/RegularExpressionValidation.cs, src/Application/Features/Payables/Commands/AddEmployment.cs, src/Application/Features/Payables/DTOs/EmploymentDto.cs, src/Server.UI/Pages/Payables/AddActivityDialog.razor, src/Server.UI/Pages/Payables/Components/Employment.razor
Raising PR for 883, changes made by @vks333
=> CFODEV-883: Added command and form for Employment, need more work

src/Application/Application.csproj, src/Application/Common/IntegrationEvents/IntegrationEvent.cs, src/Application/Features/Participants/Consumers/LogParticipantTransitionConsumer.cs, src/Application/Features/Participants/EventHandlers/PublishEnrolmentApproval.cs, src/Application/Features/Participants/IntegrationEvents/ParticipantTransitionedIntegrationEvent.cs, src/Aspire/Aspire.AppHost/Aspire.AppHost.csproj, src/Aspire/Aspire.AppHost/Program.cs, src/Aspire/Aspire.AppHost/appsettings.json, src/Infrastructure/DependencyInjection.cs, src/Infrastructure/Infrastructure.csproj, src/Infrastructure/Persistence/ApplicationDbContext.cs, src/Migrators/Migrators.MSSQL/Migrations/20241211103703_MassTransitSetup.Designer.cs, src/Migrators/Migrators.MSSQL/Migrations/20241211103703_MassTransitSetup.cs
- base integration events
- simple example
- support for RabbitMQ via MassTransit
- Adjust Aspire dependencies to use Rabbit MQ
=> CFODEV-921 Add support for integration events

src/Server.UI/Pages/Payables/AddActivityDialog.razor
Reverts ministryofjustice/CFO-CaseAssessmentTrackingSystem#359
=> Revert "activities dropdown is now searchable"

src/Infrastructure/DependencyInjection.cs, src/Server.UI/Pages/Dashboard/Components/JobManagement.razor, src/Server.UI/Pages/Dashboard/Dashboard.razor
This allows us to stop any scheduled jobs we have so we can do a deployment without them running in the background.
=> Change job dashboard so we can disable the quartz scheduler

src/Application/Common/Extensions/QueryableExtensions.cs, src/Application/Features/Outbox/Commands/RescheduleOutboxMessage.cs, src/Application/Features/Outbox/DTOs/OutboxMessageDto.cs, src/Application/Features/Outbox/Queries/PaginationQuery/OutboxMessagesWithPagination.cs, src/Application/Features/Outbox/Specifications/OutboxMessageAdvancedFilter.cs, src/Application/Features/Outbox/Specifications/OutboxMessageAdvancedSpecification.cs, src/Application/Features/Outbox/Specifications/OutboxMessageListView.cs, src/Application/Outbox/OutboxMessage.cs, src/Infrastructure/Persistence/Migrations/20250107080303_AddParentId.Designer.cs, src/Infrastructure/Persistence/Migrations/20250107080303_AddParentId.cs, src/Server.UI/Pages/SystemManagement/Outbox.razor, src/Server.UI/Services/Navigation/MenuService.cs
This pull request will show outbox messages in the UI, and you can also reschedule them.
=> Cfodev 950 ability to view and re queue outbox messages

src/Application/Common/Interfaces/Contracts/IContractService.cs, src/Application/Features/Contracts/DTOs/ContractDto.cs, src/Infrastructure/DependencyInjection.cs, src/Infrastructure/Services/Contracts/ContractService.cs, src/Server.UI/Components/Autocompletes/ContractAutoComplete.cs, src/Server.UI/DependencyInjection.cs, src/Server.UI/Pages/Payments/Components/ActivityPayments.razor, src/Server.UI/Pages/Payments/Components/EducationPayments.razor, src/Server.UI/Pages/Payments/Components/EmploymentPayments.razor, src/Server.UI/Pages/Payments/Components/EnrolmentPayments.razor, src/Server.UI/Pages/Payments/Components/InductionPayments.razor, src/Server.UI/Pages/Payments/Payments.razor, src/Server.UI/Pages/Payments/_Imports.razor, src/Server.UI/_Imports.razor
This adds graphs and a summary of paid achievements by contract.
=> Display graphs + paid

src/Application/Features/PathwayPlans/DTOs/ObjectiveDto.cs, src/Application/Features/PathwayPlans/DTOs/ObjectiveTaskDto.cs, src/Server.UI/Pages/Objectives/Objective.razor, src/Server.UI/Pages/Objectives/Tasks/ObjectiveTask.razor
=> CFODEV-1033: Add restrictions to mandatory tasks and objectives

src/Server.UI/Pages/QA/Enrolments/Components/ParticipantQaDetails.razor, src/Server.UI/Pages/QA/Enrolments/Escalation.razor, src/Server.UI/Pages/QA/Enrolments/PQA.razor, src/Server.UI/Pages/QA/Enrolments/QA1.razor, src/Server.UI/Pages/QA/Enrolments/QA2.razor, src/Server.UI/Pages/Transfers/Transfers.razor
merge #429 first.
This adds the RTW to CFO Queues regardless of consent
=> CFODEV 753 improve right to work enrolment pqa qa process

src/Application/Features/PRIs/Commands/AddActualReleaseDate.cs, src/Infrastructure/Constants/ConstantString.cs, src/Server.UI/Pages/PRIs/ActivePRIs.razor, src/Server.UI/Pages/PRIs/Components/AddActualReleaseDateDialog.razor
Added Add actual release Date dialog
Also 2 dummy buttons for Abandon and Complete PRI
=> CFODEV-1031: Dialog box to record Actual Release Date to be used on PRI tab 

src/Application/Features/PRIs/Commands/AddPRI.cs, src/Domain/Entities/PRIs/PRI.cs, src/Infrastructure/Persistence/Configurations/PRIs/PRIEntityTypeConfiguration.cs, src/Infrastructure/Persistence/Migrations/20250130073139_PRI_Add_PostReleaseCommunitySupportInformation.Designer.cs, src/Infrastructure/Persistence/Migrations/20250130073139_PRI_Add_PostReleaseCommunitySupportInformation.cs, src/Server.UI/Pages/PRIs/PRI.razor
...and added the field to the Add PRI screen
=> added PostReleaseCommunitySupportInformation field to PRI table, 

src/Application/Features/Activities/Commands/SubmitActivityPqaResponse.cs
Removed async methods from validators
=> CFODEV-987:  Prevent PQA accepting activity over 3 months old. 

src/Application/Features/QualityAssurance/Commands/SubmitPqaResponse.cs
=> Prevent PQA approving an enrolment older than 3 months. 

src/Application/Features/QualityAssurance/EventHandlers/TransitionParticipantAfterEscalationSubmissionEventHandler.cs, src/Application/Features/QualityAssurance/EventHandlers/TransitionParticipantAfterQa2SubmissionEventHandler.cs, src/Application/Features/QualityAssurance/EventHandlers/VerifyRightToWorkOnApproval.cs, src/Domain/Entities/Participants/Participant.cs, src/Domain/Events/ParticipantEvents.cs
Fixes an issue where RTW checks are not carried out when approved in Escalation queue
=> CFODEV-1080: No RTW check when approving escalation enrolments

src/Server.UI/Services/Navigation/MenuService.cs
Permission for CPMs was missing from the menu.
They already have access to the screen. Just need it to appear in the menu
=> Permission for CPMs was missing from the menu.

src/Server.UI/Pages/QA/Activities/Components/ActivityQaDetails.razor, src/Server.UI/Pages/QA/Activities/PQA.razor, src/Server.UI/Pages/QA/Enrolments/Components/ParticipantQaDetails.razor, src/Server.UI/Pages/QA/Enrolments/PQA.razor
You can now navigate directly to the participant from the QA screens
=> CFODEV-1090: Make information consistent on each of the QA screens

src/Application/Features/Activities/DTOs/EducationTrainingDto.cs, src/Server.UI/Pages/Activities/Components/EducationTraining.razor, src/Server.UI/Pages/QA/Activities/Components/ActivityQaDetails.razor
…put total, so doesnt throw exception.
=> CFODEV-1058 wrap education hyperlink

src/Infrastructure/Constants/ConstantString.cs, src/Server.UI/Pages/Participants/Components/ParticipantActionMenu.razor
This adds a menu item for senior users so a single record can be forced update.
=> Add a menu that lets senior users force sync on a single record

src/Application/Common/Interfaces/ICandidateService.cs, src/Application/Features/Candidates/Commands/SetCandidateStickyLocation.cs, src/Application/Features/Candidates/DTOs/CandidateDto.cs, src/Infrastructure/Constants/ConstantString.cs, src/Infrastructure/Persistence/Configurations/Dms/LocationMappingEntityTypeConfiguration.cs, src/Infrastructure/Persistence/Migrations/20250303114559_ExtendMappingCode.Designer.cs, src/Infrastructure/Persistence/Migrations/20250303114559_ExtendMappingCode.cs, src/Infrastructure/Services/Candidates/CandidateService.cs, src/Server.UI/Pages/Participants/Components/ParticipantActionMenu.razor, src/Server.UI/Pages/Participants/Components/SetStickyLocationDialog.razor
=> CFODEV-1061: Allow sticky community region support

src/Application/Features/Assessments/DTOs/V1/Pathways/Housing/HousingPathway.Scoring.cs
The 'Unknown' values are a median of the male and female values
=> CFODEV-1207: Fix assessment scoring for indeterminate gender

src/Application/SecurityConstants/SecurityPolicies.cs, src/Infrastructure/DependencyInjection.cs, src/Server.UI/Pages/Dashboard/Dashboard.razor.cs
Add new security policy to support system functions that only really senior users should be allowed to use
=> Add new security policy to support system functions that only really senior users should be allowed to use

src/Application/Features/ManagementInformation/IntegrationEventHandlers/RecordEnrolmentPaymentConsumer.cs, src/Application/Features/QualityAssurance/EventHandlers/PublishEnrolmentApprovedAtQaEventHandler.cs, src/Application/Features/QualityAssurance/IntegrationEvents/EnrolmentApprovedAtQaIntegrationEvent.cs
Changes the publish/subscribe for enrolment queries
=> Move to subscribing to new event.

src/Server.UI/Pages/Analytics/Components/SubmitCsoResponseComponent.razor
Question  G was using the wrong label.
=> CFODEV-1385: Fix label that the question is using.
